local Players = game:GetService("Players")
local Animate = Players.LocalPlayer.Character.Animate

-- Create a local variable for the ReplicatedStorage service
local ReplicatedStorage = game:GetService"ReplicatedStorage"

-- Create a local variable for the ChatEvent object
local ChatEvent = ReplicatedStorage.DefaultChatSystemChatEvents

-- FUNCTIONS --
local function CreateNotification(content, image, time)
	OrionLibrary:MakeNotification{
		Name = "Notification",
		Content = content,
		Image = image,
		Time = time
	}
end

local function Chat(message)
	local args = {
		[1] = message,
		[2] = "All"
	}
	ChatEvent.SayMessageRequest:FireServer(unpack(args))
end


-- Create a new window named "Neon District GUI"using DiscordLibrary
local Window = DiscordLibrary:Window("Neon District GUI")

-- Create a new server named "Utility"with the given decal URL
local Server = Window:Server("Utility", "http://www.roblox.com/asset/?id=10600607369")

-- Create a new channel named "Password"
local Channel = Server:Channel"Password"

-- Create a new textbox named "Password"with the given placeholder ChatMessage and a callback function
Channel:Textbox("Password", "Enter value here", true, function(password)
	if password == "NeonDistrict" then
					-- Create a notification with the given parameters
					CreateNotification("Access granted.", "http://www.roblox.com/asset/?id=11533060886", 5)
					local Channel = Server:Channel"Suit Control"
	
					Channel:Button("Animation", function()
			
			
						-- Set the animation IDs for each animation
						Animate.idle.Animation1.AnimationId = "rbxassetid://5319828216"
						Animate.idle.Animation2.AnimationId = "rbxassetid://5319831086"
						Animate.run.RunAnim.AnimationId = "rbxassetid://5319844329"
						Animate.walk.WalkAnim.AnimationId = "rbxassetid://5319847204"
						Animate.jump.JumpAnim.AnimationId = "rbxassetid://5319841935"
						Animate.climb.ClimbAnim.AnimationId = "rbxassetid://5319816685"
						Animate.fall.FallAnim.AnimationId = "rbxassetid://5319839762"
						Animate.swim.Swim.AnimationId = "rbxassetid://5319850266"
						Animate.swimidle.SwimIdle.AnimationId = "rbxassetid://5319852613"
			
						-- Create a notification with the given parameters
						OrionLibrary:MakeNotification{
							Name = "Notification",
							Content = "Animation applied!",
							Image = "http://www.roblox.com/asset/?id=11533060886",
							Time = 5
						}
					end)
			
					Channel:Separator()
					
					Channel:Dropdown("Outfit Picker", { "Council of Owls | Black Fedora", "Council of Owls | Hair", "Antebellum Briefcase"}, function(OutfitChosen)
					if OutfitChosen == "Council of Owls | Black Fedora" then
						OrionLibrary:MakeNotification{
							Name = "Notification",
							Content = "Outfit changed!",
							Image = "http://www.roblox.com/asset/?id=11533060886",
							Time = 5
						}
						ReplicatedStorage.Events.remove_Player_Outfit:InvokeServer()
						local args = {
							[1] = -1,
							[2] = {
								[1] = "533915049",
								[2] = "533798013",
								[3] = "5728208977",
								[4] = "8526979460"
							}
						}
						ReplicatedStorage.Events.customizePlayer:InvokeServer(unpack(args))
					elseif OutfitChosen == "Council of Owls | Hair" then
						OrionLibrary:MakeNotification{
							Name = "Notification",
							Content = "Outfit changed!",
							Image = "http://www.roblox.com/asset/?id=11533060886",
							Time = 5
						}
						ReplicatedStorage.Events.remove_Player_Outfit:InvokeServer()
						local args = {
							[1] = -1,
							[2] = {
								[1] = "533915049",
								[2] = "533798013",
								[3] = "5891039736",
								[4] = "8526979460"
							}
						}
						ReplicatedStorage.Events.customizePlayer:InvokeServer(unpack(args))
						elseif OutfitChosen == "Antebellum Briefcase" then
							Chat("I deployed the retractable legs of the Antebellum briefcase by pressing the corresponding button on the side of the case. The legs extended vertically in a synchronized manner, following the order in which they were deployed.")
							wait(2.5)
							Chat("The framework of the case was galvanized and coated with an obsidian finish that gleamed along its polished matte-black surface.")
							wait(2.5)
							Chat('I announced the word "Arsenal" while facing the briefcase, and a mechanical whir engaged from inside as the lock disengaged and fell into place with a satisfying metallic thud.')
							wait(2.5)
							Chat("The lining of the case is divided into two sections that allow it to open with a soft hiss as air rushes into the depressurized compartment.")
							wait(2.5)
							Chat("I reached into the briefcase and grabbed the plate carrier, swiftly slipping it over my suit and securing the fasteners with a satisfying click.")
							wait()
							local args = { 
							[1] = -1, 
							[2] = { 
							[1] = "7246494294", 
							[2] = "10730111839"
								} 
							}
							ReplicatedStorage.Events.customizePlayer:InvokeServer(unpack(args))
							wait(2.5)
							Chat("I then grasped the tactical assault pack by its rim strap and slid it across my waist, securing it with the buckle and collar latch.")
							wait()
							local args = { 
								[1] = -1, 
								[2] = { 
									[1] = "6741098749"
									} 
								}
								ReplicatedStorage.Events.customizePlayer:InvokeServer(unpack(args))
					end
				end)

					Channel:Separator()

					-- Declare the QuotationsEnabled variable at the top of the script
					local QuotationsEnabled = false

					-- Define the hook function
					local CreateHookNamecall
					CreateHookNamecall = hookmetamethod(game, "__namecall", function(self, ...)
						local method = getnamecallmethod()
						local args = {...}

						if not checkcaller() and self.Name == "SayMessageRequest" and method:lower() == "fireserver" then
							-- Use the QuotationsEnabled variable to determine whether or not to add double backticks separated with a space around the first argument
							return CreateHookNamecall(self, (QuotationsEnabled and '`` | ' or "")..args[1]..(QuotationsEnabled and ' | ``' or ""), args[2])
						end
						
						return CreateHookNamecall(self, ...)
					end)


					-- Pass the ToggleQuotations function as an argument to the Channel:Toggle function
					Channel:Toggle("Speech", true, function(Status)
					QuotationsEnabled = Status
					end)


					local Server = Window:Server("Location", "http://www.roblox.com/asset/?id=10600605142")
					local Channel = Server:Channel"Checkpoint"
					Channel:Button("Identification", function()
					Chat("I flicked my arm over, a mattle-black virtual OS-independent card whipping out of my sleeve in a fluid motion.")
					wait(2.5)
					Chat("I raised it up to you and with it came an embedded message: 'NSA Intelligence Officer - SCD - Strategic Communication Directive | SSO - State Security Operative'")
					end)
			
					local Channel = Server:Channel"Residential Region"
					Channel:Button("Market & Tower", function()
					Chat("The blue-hued light emanating from the phone booth highlights my suit whilst a delineation of my physique manifested on the pavement.")
					wait(2.5)
					Chat("The scarlet radiance emanating from the bamboo-framed paper lanterns hanging above the pavement serves as a testament to the vibrant and diverse Asian culture present in this bustling district.")
					wait(2.5)
					Chat("Vibrant lights coming from the advertisements scattered across the pavement clash and overlap in the air, formulating a dazzling display of shifting gradient hues.")
					wait(2.5)
					Chat("The statesque Watch Tower stood guard overhead, its iconic message and symbol flashing and changing across the pulsing display.")
					end)
			
					Channel:Button("Retail Avenue", function()
					Chat("I strode past the sleek and imposing bollard fencing, my tall and agile silhouette cutting a sharp figure against the cars parked on the street.")
					wait(2.5)
					Chat("The vibrant and frenetic energy of the city pulsed around me, a living, breathing organism fueled by advanced technology and a thirst for progress.")
					wait(2.5)
					Chat("The flashy advertisement boxes pulsed with light on the dimly-lit sidewalk, illuminating the grimy and cluttered trench that ran along the ground and exposed the clutter of pipes and wires.")
					wait(2.5)
					Chat("The gleaming retail establishments that lined the bustling sidewalk flared with luminescence, casting a dazzling array of shifting colors across the frenetic commercial lane.")
					end)
			
					local Channel = Server:Channel"Construction Site"
					Channel:Button("Walk", function()
					Chat("I walked past fencing adorned with intricate and shimmering holographic construction barriers blocking the road and forcing me to detour through one of the three narrow scaffolding shafts.")
					wait(2.5)
					Chat("A heap of lumber lay in repose, adjacent to a steam-powered road compactor. The thoroughfare had been damaged and divided by a series of low barriers.")
					wait(2.5)
					Chat("The two pipes, both of which were in a state of disrepair, had been compromised by the passage of time and the relentless onslaught of urbanization.")
					wait(2.5)
					Chat("The first pipe, its surface scarred and pitted by corrosion, was clearly in dire need of replacement, its once-smooth exterior now rough and jagged.")
					wait(2.5)
					Chat("The second pipe, though not as visibly damaged as its counterpart, was nonetheless leaking copious amounts of liquid, its metallic walls unable to withstand the pressure of the flowing contents.")
					wait(2.5)
					Chat("Together, these two pipes represented a microcosm of the decay and entropy that permeated the world of the future, a grim reminder of the ravages of time and the fleeting nature of all things.")
					wait(2.5)
					Chat("It is an incontrovertible fact that the absence of supervision and adequate illumination, among other deficiencies, clearly illustrates the dire state of workplace safety protocols in this depraved society.")
					wait(2.5)
					Chat("The dilapidated condition of the District's utility infrastructure was a clear indication of a deficiency in the level of consistent and thorough upkeep and maintenance efforts.")
					end)
			
					local Channel = Server:Channel"Lone Ranger"
					Channel:Button("Enter Bar", function()
					Chat("As I entered the establishment, I carefully placed one foot in front of the other, moving with a refined stride.")
					wait(2.5)
					Chat("My hand rose with a fluid motion, my fingers curling around the sleek metal framework of my mask as I walked.")
					wait(2.5)
					Chat("I carefully and deliberately drew the mask upwards until it was pressing against the brim of my fedora.")
					wait(2.5)
					Chat("The light in the room shifted to a green hue, and a low hum filled the air as a result of the subpar lightbulb.")
					wait(2.5)
					Chat("The persistent, pungent odor of smoke and other airborne contaminants permeated the atmosphere of the enclosure but was paradoxically juxtaposed with the pervasive scent of rain.")
					wait(2.5)
					Chat("This olfactory dichotomy was indicative of the industrialization and environmental degradation of the city.")
					end)
			
					Channel:Separator()

					Channel:Button("Take Seat | Stool", function()
					Chat("Behind the bar, a glass partition serves to demarcate the entrance hall from the bar, and in the middle of this partition, there is an elegant display of bottles that fulgurated in the verdant light.")
					wait(2.5)
					Chat("I ambulate towards the designated seating area, resolutely affirming my state of composed demeanor as I do so.")
					wait(2.5)
					Chat("As I deign to descend, I permit my vassal to sink into a perpendicular position, my lower extremities straddling the seat of the stool.")
					wait(2.5)
					Chat("The heft of my mass exerts a compressing force upon the pliable leather, causing it to irrevocably conform to my form and create a deeply curved indentation in the seat.")
					end)

					Channel:Button("Take Seat | White Tailored Cushion", function()
					Chat("As I approach the designated seating area, my gait exudes a sense of dignified poise, my center of mass traversing the euclidean plane with aplomb.")
					wait(2.5)
					Chat("I oblige with the invitation, my lower extremities initiating contact with the white tailored cushion, its surface area conforming to the contours of my derriere.")
					wait(2.5)
					Chat("The cushion's pliability and compressibility yield to the heft of my mass, creating a concave indentation, the result of the cushion's deformation under the force exerted by my body.")
					end)

					Channel:Separator()
			
					Channel:Button("Order Drink | Player", function()
					Chat("As I engaged in a thorough analysis of the proprietor of the establishment, I inclined my physical form toward the counter.")
					wait(2.5)
					Chat("Its exterior surface exhibited a lustrous and highly reflective quality due to its construction from pristine marble.")
					wait(2.5)
					Chat("The suave caress of fine sartorial adornment enveloped my digits as I elegantly inserted my limb into the discreet compartment of my attire, my digits grazing the slick surface of the material.")
					wait(2.5)
					Chat("Utilizing adroit manipulation, I extracted a glistening E-Cash card, its electronic facade radiant in the luminosity of the establishment, saturated with the radiance of the sun's rays.")
					wait(2.5)
					Chat('"Good evening,"I intoned, my voice scarcely above a dulcet monotone as I addressed the proprietor of the establishment.')
					wait(2.5)
					Chat('"Just a glass of Oxy."A statement I said in a phlegmatic tone directed towards the barkeep. My request is terse, yet suffused with a glacial aura that belies a subconscious desire for incentives.')
					wait(2.5)
					Chat("With the swiftness of a venomous serpent, my limb extended rapidly as I presented my financial instrument at the counter with the utmost .")
					end)
			
					Channel:Button("Order Drink | NPC | Counter", function()
					Chat("As I engaged in a thorough analysis of the proprietor of the establishment, I inclined my physical form towards the counter")
					wait(2.5)
					Chat("Its exterior surface exhibited a lustrous and highly reflective quality due to its construction from pristine marble.")
					wait(2.5)
					Chat('The suave caress of fine sartorial adornment enveloped my digits as I elegantly inserted my limb into the discreet compartment of my attire, my digits grazing the slick surface of the material.')
					wait(2.5)
					Chat("Utilizing adroit manipulation, I extracted a glistening E-Cash card, its electronic facade radiant in the luminosity of the establishment, saturated with the radiance of the sun's rays.")
					wait(2.5)
					Chat('"Good evening," I intoned, my voice scarcely above a dulcet monotone as I addressed the proprietor of the establishment.')
					wait(2.5)
					Chat('"Just a glass of Oxy."A statement I said in a phlegmatic tone directed towards the barkeep. My request is terse, yet suffused with a glacial aura that belies a subconscious desire for incentives.')
					wait(2.5)
					Chat("With the swiftness of a venomous serpent, my limb extended rapidly as I presented my financial instrument at the counter with the utmost .")
					wait(2.5)
					Chat("The expert tapster approached the towering edifice of the state-of-the-art beverage distribution system, their digits gracefully grasping the circumference of a robust decanter.")
					wait(2.5)
					Chat("Their boots reverberated against the grimy floorboards, their sight locked onto the spectrum of liquid that seeked to quench the insatiable cravings of their clientele.")
					wait(2.5)
					Chat("As they approached the refreshment dispenser, they extended their limb towards it, their digits deftly maneuvering across the buttons and levers that would trigger a deluge of  liquid.")
					wait(2.5)
					Chat("The lever was activated with a swift, calculated gesture, initiating the release of a torrential flow of liquid from the dispenser, inundating the glass with a copious amount of the fluid.")
					wait(2.5)
					Chat("As they progressed with measured, lugubrious steps, they retraced their steps, returning to the counter with a plodding and calculated pace.")
					wait(2.5)
					Chat("They approached, their limb extended forth, deftly sliding the crystalline vessel across the plane with a sinuous, sophisticated motion.")
					wait(2.5)
					Chat("The motion of the glass sliding across the counter generated a harsh, grating screech, coming to a halt with a dull clack.")
					end)

					Channel:Button("Order Drink | NPC | Couch", function()
					Chat("Utilizing adroit manipulation, I extracted a glistening E-Cash card, its electronic facade radiant in the luminosity of the establishment, saturated with the radiance of the sun's rays.")
					wait(2.5)
					Chat("The expert tapster approached me with swift steps, their sight locked onto the spectrum of liquid that seeked to quench the insatiable cravings of their clientele.")
					wait(2.5)
					Chat('"Good evening," I intoned, my voice scarcely above a dulcet monotone as I addressed the proprietor of the establishment.')
					wait(2.5)
					Chat('"Just a glass of Oxy." A statement I said in a phlegmatic tone directed towards the barkeep. My request is terse, yet suffused with a glacial aura that belies a subconscious incentive.')
					wait(2.5)
					Chat("As they approached the refreshment dispenser, they extended their limb towards it, their digits deftly maneuvering across the buttons and levers that would trigger a deluge of liquid.")
					wait(2.5)
					Chat("The lever was activated with a swift, calculated gesture, initiating the release of a torrential flow of liquid from the dispenser, inundating the glass with a copious amount of the fluid.")
					wait(2.5)
					Chat("As they progressed with measured, lugubrious steps, they retraced their steps, returning to the seating area with a plodding and calculated pace.")
					wait(2.5)
					Chat("They approached, their limb extended forth, deftly sliding the crystalline vessel across the plane with a sinuous, sophisticated motion.")
					wait(2.5)
					Chat("The motion of the glass sliding across the tabletop generated a harsh, grating screech, coming to a halt with a dull clack.")
					end)
			
					Channel:Button("Drink", function()
					Chat("I extended my arm to its full length and wrapped my fingers around the glass, the movement resembling an elegant curve as my digits enveloped it.")
					wait(2.5)
					Chat("I brought the vessel to my mouth and positioned its rim against my lips, readying myself to consume its liquid payload.")
					wait(2.5)
					Chat("With an almost parallax-mannered transition, I permitted the liquid to flow within.")
					wait(2.5)
					Chat("As I lavish in the rich and indulgent experience of dissipating the tasteless beverage, I let out a contented sigh and returned the vessel to its designated location upon the counter.")
					wait(2.5)
					Chat("Upon the base of the crystalline vessel making contact with the countertop, a frothy and bubbly commotion ensues within the liquid contained therein.")
					wait(2.5)
					Chat("The substances within engage in a tumultuous interplay of physical and chemical reactions, swirling and churning in a frenzied dance.")
					wait(2.5)
					Chat("The viscosity of the liquid seems to be affected by a continual process of deformation, forming elaborate configurations and convoluted eddies when illuminated.")
					wait(2.5)
					Chat("It is as if the liquid were endowed with an animating essence, exhibiting a frenzied and convulsive exultation as it undulates and contorts in an unpredictable and irrational manner.")
					wait(2.5)
					Chat("The fluid behaves like a frenetic and ungovernable creature, eschewing all foresight and rationale.")
					wait(2.5)
					Chat("It is a privilege to behold the entirety of the scene before us, a spectacle that can be described as both enthralling and intimidating.")
					wait(2.5)
					Chat("Through our gaze, we are given a brief window into a realm of primal energies that are beyond the limits of our comprehension and agency.")
					wait(2.5)
					Chat("It is a realm of raw power and unbridled forces, one that instigates both a sense of both fascination and fear.")
					wait(2.5)
					Chat("I peruse the chamber, attentively examining each individual aspect with utmost exactitude, assimilating each minute oscillation of the customers present.")
					wait(2.5)
					Chat("Each kineticism made by the crowd, every alteration in bodily position or fleeting glance was recorded in my cognitive processes as if it were a fragment of data within an interlinked system.")
					wait(2.5)
					Chat("The limb extending from my shoulder joint, clad in a sleek, protective integument, advances in a gradual manner, the slender vessel fabricated from crystalline material still held by the limb.")
					wait(2.5)
					Chat("Utilizing a dexterity indicative of a machine, I manipulate the glass towards my oral cavity and, with a single, smooth motion, imbibe the entire liquid contained within.")
					wait(2.5)
					Chat("The resounding clink of the glass reverberated through the sterile establishment, summoning to mind the echoes of ancient Greek philosophers debating within the hallowed halls of the agora.")
					wait(2.5)
					Chat("As the glass descended towards the counter, its lower circumference made contact with the inflexible stone, emitting a subtle tremor that tore the hitherto motionless atmosphere.")
					end)

					Channel:Button("Stand Up | Stool", function()
					Chat("I disengage my lower extremities from their straddled position atop the stool, utilizing multiple actuators to smoothly execute a vertical displacement.")
					wait(2.5)
					Chat("The stool, rendered pliant by my mass, bounces elastically as I depart, its surface area returning to its original configuration.")
					wait(2.5)
					Chat("My center of mass, now elevated, is propelled forward by the propulsive force generated by the contraction of my leg extensors, allowing me to traverse the euclidean plane with an economy of motion.")
					end)
	
					Channel:Button("Stand Up | White Tailored Cushion", function()
					Chat("The couch, rendered pliant by my mass, conforms elastically as I depart, its surface cushion returning to its initial state.")
					wait(2.5)
					Chat("As I secure my grasp on the armrest of the white-cushioned couch, I exert a  propelling force, hurling my body upwards in a controlled manner. ")
					wait(2.5)
					Chat("I am able to seamlessly erect myself, transitioning from a seated position to an upright stance.")
					end)
			
					local Channel = Server:Channel"Plaza"
					Channel:Button("Walk", function()
					Chat("As I progressed along my path, the majestic, foreboding archway arose before me, its irregular, carelessly assembled train tracks suspended in a perilous manner above my head.")
					wait(2.5)
					Chat("The verdant luminescence emanating from the metal ventilations had an almost otherworldly quality, as if it were the result of some archaic, occult technology.")
					wait(2.5)
					Chat("The effulgence emanating from the lamp beneath the tumultuous flow of excremental matter pulsated and circulated, emitting a faint, supernatural radiance.")
					wait(2.5)
					Chat("As the luminous radiation traversed the undulating aqueous medium, it was refracted and contorted, generating a hypnotic exhibition of refracted oscillations and configurations.")
					wait(2.5)
					Chat("Amidst the chaotic hubbub of the grand market square, the effigy of the dragon, with its immense, commanding presence, towers above all else, reminiscent of the ancient Greek myth of the Chimera.")
					wait(2.5)
					Chat("Despite its commonality, the sculpture constantly invokes a sense of wistful longing, its every curve a tribute to the unending inventiveness of the parasitic Asian culture that feeds on the District.")
					wait(2.5)
					Chat("As the vestibule of the shop materialized before them, the windows, reflecting the luminosity of the day's solar rays, displayed a resplendent array of screens that flickered with a hypnotic allure.")
					wait(2.5)
					Chat("As the luminous cathode rays flickered and shimmered within the antique television sets of yore, the ephemeral images on the screens were prone to fleeting distortions and aberrant coalescence.")
					wait(2.5)
					Chat("The air was filled with an incessant hum of electronic noise emanating from the local news and weather channels, the reports and forecasts of which played on a continuous loop.")
					wait(2.5)
					Chat("The oft-neglected parking space contained within its borders a serene region that bore a striking resemblance to a picturesque yet cosmopolitan structure that extended far and wide.")
					wait(2.5)
					Chat("Amidst the cacophony and frenetic energy of the metropolis, this verdant refuge seemed an idyllic, tranquil respite.")
					end)
			
					Channel:Button("Big Crowd", function()
					Chat("The discordant noise emanating from the unenthused assemblage reverberated throughout the locale, summoning visions of a typical occurrence in which a tumultuous throng had gathered.")
					wait(2.5)
					Chat("The cacophonous palaver emanating from the gathered individuals was a clear indicator of their lack of engagement and the inane discourse they engaged in served to amplify the atmosphere of apathy.")
					wait(2.5)
					Chat("The palpable atmosphere of this location was one in which the suppression of personal uniqueness and the valorization of conforming to societal standards was the modus operandi.")
					end)
					
					Channel:Button("Small Crowd", function()
					Chat("The modest posse of the populace accumulated in the vicinity of the plaza constructed an ataractic setting, where the constant noise was faint.")
					end)
			
					Channel:Button("No Crowd", function()
					Chat("The absence of any presence created a quiescent scenery as the tranquil state of the plaza was infrequent during this juncture of time.")
					end)
			
					local Channel = Server:Channel"Alleyway"
					Channel:Button("Walk", function()
					Chat("It was a harmonious amalgamation of auditory and kinetic phenomena, the unbroken drone of the metropolis being interrupted by the regular percussion of the precipitation.")
					wait(2.5)
					Chat("As the rain falls upon the ground, its rhythmic percussion resonates throughout the narrow passageway, the distinct plashes of each droplet standing out amid the din of sound.")
					wait(2.5)
					Chat(" The flow of liquid through the earth is in a manner akin to small channels, coalescing in areas of concavity and becoming confined within the fissures and indentations of the man-made substrate.")
					wait(2.5)
					Chat("Languidly reposing within the confines of the dilapidated and ruinous garage door, there was exhibited a flicker of constrast - a bicycle of sleek and lustrous appearance.")
					wait(2.5)
					Chat("A poignant and evocative recollection of the discarded detritus of our bygone era, left in the wake of its passage.")
					wait(2.5)
					Chat("As the lucent reflection of the bicycle's framework captured the illumination, it is impossible not to feel a sense of reverence for the way in which it embodies the restricted potential of progress.")
					wait(2.5)
					Chat("The dilapidated state of the garage door, with its corroded surface and crumbling appearance, formed a vivid juxtaposition to the sophisticated machinery that stood before it.")
					wait(2.5)
					Chat("Despite their seemingly incongruous co-presence, the conjunction of these served to exemplify the multifacetedassociation between the human race and its artificially-constructed counterparts.")
					wait(2.5)
					Chat("The ebullient scarlet veil that envelops the exterior of the noodle emporium is a discrete yet captivating tribute to the grandiose dragon that is prominently exhibited within its walls.")
					wait(2.5)
					Chat("The elaborate bamboo scaffolding of the paper lantern suspended above us serves as a visible manifestation of the cultural forces that have molded the culinary offerings of this establishment.")
					wait(2.5)
					Chat("As I navigate the narrow passageway, my eyes are naturally drawn to the ground below, where a single wire of lemon hue writhes and contorts in agony, having been violently severed from its origin.")
					wait(2.5)
					Chat("Unflinching in the face of the abominable visage before me, I nimbly traverse its repugnant form, my destination the workshop of automotive engineering unerringly in my sights.")
					wait(2.5)
					Chat("As I traversed the seemingly interminable corridor of habitations, its elongated expanse ultimately led me to the side of a financial establishment.")
					wait(2.5)
					Chat("The visage of the financial institution's exterior is aesthetically crafted with the intention of utilizing a marble motif, so as to ensnare the gaze of potential patrons.")
					wait(2.5)
					Chat("When the invocative shades of verdant hues are artfully positioned, it serves to impart a perception of protection and reliability.")
					wait(2.5)
					Chat("The utilization of this particular artistic expression is calculated to serve as a means of advertisement, designed to elevate the public perception of the establishment and its offerings to those who happen upon it in their travels.")
					end)
			
					local Channel = Server:Channel"Urban Subsector"
					Channel:Button("Walk", function()
					Chat(" Upon my arrival in the bustling metropolis, I was greeted by the abundance of commercial endeavors that lined the thoroughfares.")
					wait(2.5)
					Chat("An establishment displayed their motorcycles in an ostentatious manner, with the vehicles being elevated upon pedestals and encased within display cases.")
					wait(2.5)
					Chat("The bright and flashy scintillation augmented the magnanimous exhibition, added to the grandiose display, drawing attention to itself.")
					wait(2.5)
					Chat("The radiant illumination emanating from the beacon of Lee's Defense cascaded past my corporeal form.")
					wait(2.5)
					Chat("A pulsating and shimmering effulgence was cast upon the pool of precipitation that had aggregated upon the ground.")
					end)
			
					Channel:Button("Turn To Alleyway", function()
					Chat("I rotated my body in the direction of the change in the path, approaching the intersection adjacent to the esteemed BE Fashion establishment.")
					wait(2.5)
					Chat("The threadbare ventilator, a mechanical entity in dire need of maintenance, was affixed to the corroded air duct within the partitioned alleyway.")
					wait(2.5)
					Chat("The graffito, in a state of deterioration, which adorned the walls served only to augment the desolate and forlorn ambiance of the lane.")
					end)
			
					Channel:Button("Turn To Stairway", function()
					Chat(" I oriented my physical form towards the direction of the right, taking pains to position each ambulatory stride as I leisurely traversed within the subterranean passageway.")
					wait(2.5)
					Chat("The stagnant atmosphere within the confines of the structure was a startling collocation to the perpetual deluge beyond its walls.")
					end)
			
					Channel:Button("Ascend Stairway", function()
					Chat("s I traversed the metallic steps of the ascending staircase with calculated exactitude, I gradually ascended to the upper echelon of the floor above.")
					end)
			
					local Channel = Server:Channel"Fresh Cups"
					Channel:Button("Enter Cafe", function()
					Chat("With a poised rotation of my personage, I pivot towards the Fresh Cups cafe, gliding towards the entrance with svelte accuracy.")
					wait(2.5)
					Chat("The graceful redistributions of my physical form's gravitational center permit me to effortlessly navigate around the temporary barricade of construction fencing.")
					wait(2.5)
					Chat("The metallic handle, cool to the touch, yielded to the firm grasp of my fingers as I wrenched the door open, causing it to swing outward in a manner reminiscent of a pendulum.")
					wait(2.5)
					Chat("The bell, affixed to the roof of the edifice in a most conspicuous manner, emitted a sonorous chime as I crossed the threshold into the cafe, announcing my presence to all within earshot.")
					wait(2.5)
					Chat("The cafe's atmosphere was carefully cultivated to facilitate a tranquil resolution, a haven from the tumultuous exterior world.")
					wait(2.5)
					Chat("The delicate scent of gently caramelized caffeine permeates the air, offering a subtle yet alluring olfactory experience to the patrons.")
					end)
			
					Channel:Button("Order Mochaccino", function()
					Chat("As I release a breath, the condensation from the freezing rain-soaked air escapes my lips, leaving a vapor trail in its wake.")
					wait(2.5)
					Chat("I then leisurely make my way towards the counter, giving a subtle nod to the barista to indicate my presence.")
					wait(2.5)
					Chat("As I carefully peruse the contents of the antiquated chalkboard, I am struck by the array of beverages and meals inscribed upon it.")
					wait(2.5)
					Chat("The letters and numbers etched into its onyx-hued surface in a manner that evoked a sense of nostalgia.")
					wait(2.5)
					Chat("I now redirected my gaze to the barista, slipping my hand into the fabric slit on my suit. I would remove an E-Cash card. ‟A mochachinno, please.” I nodded my head to the barista behind the counter.")
					wait(2.5)
					Chat("The barista, recognizing my intention, reached out with their own hand and deftly took hold of the E-cash card, deftly inserting it into the card reader that was integral to their business.")
					wait(2.5)
					Chat("After the precise amount of credits had been extracted from the credit card, the barista extended their arm in my direction")
					wait(2.5)
					Chat("They offered me the opportunity to reclaim possession of said card by clasping it securely within my clutch.")
					wait(2.5)
					Chat("The barista carefully placed the raven-tinted heat-regulating mug onto the sleek, metallic countertop.")
					wait(2.5)
					Chat("In unison, the barista then placed a small souffle cup filled with delicate microfoam milk.")
					wait(2.5)
					Chat("The frothy substance gently cascading over the sides as it too made contact with the counter.")
					wait(2.5)
					Chat("I grasped the mug with my fingers, feeling the contoured curve of its handle fit snugly into my palm.")
					wait(2.5)
					Chat("The souffle cup, with its delicate margin, was gently lifted from its previous resting place and maneuvered through the air.")
					end)
			
					Channel:Button("Order Black Coffee", function()
					Chat("As I release a breath, the condensation from the freezing rain-soaked air escapes my lips, leaving a vapor trail in its wake.")
					wait(2.5)
					Chat("I then leisurely make my way towards the counter, giving a subtle nod to the barista to indicate my presence.")
					wait(2.5)
					Chat("As I carefully perused the contents of the antiquated chalkboard, I was struck by the array of beverages and meals that were inscribed upon it.")
					wait(2.5)
					Chat("The letters and numbers etched into its onyx-hued surface in a manner that evoked a sense of nostalgia.")
					wait(2.5)
					Chat("I now redirected my gaze to the barista, slipping my hand into the fabric slit on my suit. I would remove an E-Cash card. ‟Black; two sugars, please.” I nodded my head to the barista behind the counter.")
					wait(2.5)
					Chat("The barista, recognizing my intention, reached out with their own hand and deftly took hold of the E-cash card, deftly inserting it into the card reader that was integral to their business.")
					wait(2.5)
					Chat("After the precise amount of credits had been extracted from the credit card, the barista extended their arm in my direction")
					wait(2.5)
					Chat("They offered me the opportunity to reclaim possession of said card by clasping it securely within my clutch.")
					wait(2.5)
					Chat("The barista carefully placed the raven-tinted heat-regulating mug onto the sleek, metallic countertop.")
					wait(2.5)
					Chat("In unison, the barista then placed a small souffle cup filled with delicate microfoam milk.")
					wait(2.5)
					Chat("The frothy substance gently cascading over the sides as it too made contact with the counter.")
					wait(2.5)
					Chat("I grasped the mug with my fingers, feeling the contoured curve of its handle fit snugly into my palm.")
					wait(2.5)
					Chat("The souffle cup, with its delicate margin, was gently lifted from its previous resting place and maneuvered through the air.")
					end)
			
					Channel:Button("Take Seat In Beanbag", function()
					Chat("I placed both of the cups onto the beanbag-assigned table, smoke emanating from the mug.")
					wait(2.5)
					Chat("I began to let myself fall onto the beanbag, the material immediately concaving around my body engulfing a portion of it.")
					end)
			
					Channel:Button("Take Seat In Chair", function()
					Chat("I placed both of the cups onto the cantilever-chair assigned table, smoke emanating from the mug.")
					wait(2.5)
					Chat("I began lowering my waist level, seating myself onto the cantilever chair, and resting my vertebral column on its backrest.")
					end)
			
					Channel:Button("Drink", function()
					Chat("I clasped my fingers onto the margin of the souffle cup once more, lifting it just above the rim of the mug.")
					wait(2.5)
					Chat("I poured the microfoam proficiently into a pattern resembling a 5-layered rosetta.")
					wait(2.5)
					Chat("I now transferred my grip onto the handle of the mug, fastening my fingers on its verge and bringing its rim closer to my lips.")
					wait(2.5)
					Chat("I took a sip from the mug, feeling a wave of serenity wash over me. The heat from the drink was tolerable.")
					wait(2.5)
					Chat("Repeating this process, I eventually finished my drink.")
					end)
			
					local Channel = Server:Channel"Amery | Normal"
					Channel:Button("Enter Building", function()
					Chat("My feet shifted in a fluid movement, each step producing a gentle thud as the surfaces collided.")
					wait(2.5)
					Chat("A very faint, almost imperceptible flow of air resembling a vapor had accompanied my entry through the door, but it was no longer detectable.")
					wait(2.5)
					Chat("However, the enduring aroma of rain was still present and seemed to continuously exist.")
					end)
			
					Channel:Button("Enter Hallway", function()
					Chat("I proceeded to walk towards the door in a confident manner, positioning my fingers in a curled position around the cold, metallic handle.")
					wait(2.5)
					Chat("As I touched the handle with my palm, I gently pulled on it, causing it to open and allow me to pass through the doorway.")
					wait(2.5)
					Chat("I entered the glass-framed hallway through the doors, wherein the scent of rain didn't advance any further.")
					wait(2.5)
					Chat("As I progressed down the corridor, which was illuminated with only a faint level of light, I eventually reached the entryway to the decontamination chamber.")
					wait(2.5)
					Chat("The transparent container was providing an unobstructed view of the continuous precipitation occurring beyond its surface.")
					wait(2.5)
					Chat("As the water droplets fall from the sky and make contact with the glass, they traverse down its exterior, leaving a discernible path in their wake.")
					wait(2.5)
					Chat("I proceeded in the direction of the decontamination chamber, noticing that the sound of my footsteps caused a series of repetitive, gentle pounding noises.")
					end)
			
					Channel:Button("Enter Chamber", function()
					Chat("I lifted my arm upwards, positioning it in a manner that allowed for the scanner to access the card within a convenient range for the scanning process to be initiated.")
					wait(2.5)
					Chat("I performed a rapid, whipping motion with my hand, causing the card to be extracted from my grasp and thrust into the designated receptacle on the scanner.")
					wait(2.5)
					Chat("As I manipulated the card in this manner, I could see the tiny opening on the scanner, which was meant to receive the card for analysis.")
					wait(2.5)
					Chat("As the card came into contact with the scanner, a process of validation began, the scanner utilizing an dynamic data-vault to determine the authenticity of the card.")
					wait(2.5)
					Chat("As this process reached its conclusion, a bright, verdant glow emanated from the scanner, signifying that the card had been deemed valid")
					wait(2.5)
					Chat("The gate began its upward trajectory, a sound reminiscent of a hissing serpent from within the chamber as the air pressure within began to dissipate.")
					wait(2.5)
					Chat("As I make my way into the designated chamber, I am immediately greeted by the presence of chlorine dioxide gas and vapor phase hydrogen peroxide.")
					wait(2.5)
					Chat("They were in the process of being dispersed from the gas dispensers in an effort to thoroughly decontaminate my person prior to granting me access to the interior of the facility.")
					wait(2.5)
					Chat("The gas diminishes just as the chamber door opens once more, granting enough time for me to walk through.")
					end)
			
					Channel:Button("Wings", function()
					Chat('Upon entering the facility, I am greeted by a smaller side-wing which has been labeled "Security."')
					wait(2.5)
					Chat("Within this particular area, I observe a mobile artillery unit that has been stationed there, as well as a variety of weapons that have been mounted on the walls.")
					wait(2.5)
					Chat("The positioning and arrangement of these objects seemed to suggest a strong emphasis on the safeguarding the premises, indicating a subconscious awareness of the presence of assets.")
					wait(2.5)
					Chat("The area was sealed from access by a reinforced glass wall, the likes that are not obtainable by the public.")
					wait(2.5)
					Chat("The observing station, which is located adjacent to the counter, allows for examination by security personnel, who are equipped with the capability to restrict access to certain individuals.")
					wait(2.5)
					Chat('It is possible to discern yet another wing located in the more remote corner of the facility, which has been designated as the "Experimental"wing')
					wait(2.5)
					Chat("This particular wing has been equipped with a protective covering of padding that extends from the floor to the ceiling.")
					wait(2.5)
					Chat("The room contained Cryo-Containment technology, which was exemplified by the presence of capsules wherein organic materials were placed for the purpose of being conserved in a state of maintenance.")
					wait(2.5)
					Chat('Located on the eastern side of the room was a counter that afforded a view of the so-called "Ghost Pods". Adhered to metallic protuberances were panels displaying various data.')
					wait(2.5)
					Chat("A holographic display featuring a representation of a DNA Helix prominently displayed novel strains within the gene sequence, thereby indicating an aberration within the structure's configuration.")
					end)
			
					Channel:Button("Calculation Workspace", function()
					Chat("The chalkboard composed a discourse on the utilization of the equations as a medium for the display and organization of mathematical and scientific data.")
					wait(2.5)
					Chat("And with it came a particular emphasis on the various forms of representation exemplified by the notations and diagrams present on the surface of the board.")
					wait(2.5)
					Chat("To utilize a highly technical and exacting language, incorporating specialized terminology and syntactical constructions to convey a sense of sophistication for convenience was complex in itself.")
					wait(2.5)
					Chat("Two chairs were situated on the workplace flooring so as to emulate a lecture regarding the demonstrated connotations.")
					end)
			
					Channel:Button("Papers Workspace", function()
					Chat("Another workspace parallel to the aforementioned subject gave a passive elucidation to the nature of this laboratory.")
					wait(2.5)
					Chat("The stacks of documents: archives, dossiers, directories, invoices, portfolios; accentuated by the yellow glare from the dual-monitors branching in between them.")
					end)
			
					Channel:Button("VR Workspace", function()
					Chat("Another station equidistant to this exhibited an omni-directional treadmill, a VR headset, and monitors displaying the status of the on-going simulation.")
					end)
			
					Channel:Button("Tool Workspace", function()
					Chat("The final station was consubstantial in nature to the other workplaces, presenting an antediluvian aura by virtue of the treadmill, worn-out wrench, and disjoined appendages.")
					end)
			
					local Channel = Server:Channel"Amery | Banquet"
					Channel:Button("Enter Building", function()
					Chat("My feet shifted in a fluid movement, each step producing a gentle thud as the surfaces collided.")
					wait(2.5)
					Chat("The faint, vapor-like current of air that had followed me in through the door was no longer evident, yet the lingering fragrance of rain remained, ever-present as it appeared.")
					end)
			
					Channel:Button("Set Atmosphere", function()
					Chat("As the grandiose notes of the string quintet's movement echoed throughout the spacious interior of the edifice, a sense of liveliness permeated the atmosphere within the structure.")
					wait(2.5)
					Chat("The sublime slowness of the musical piece, evocative of the ethereal beauty of the natural world, seemed to imbue the very air with a sense of serenity and tranquility.")
					wait(2.5)
					Chat("In conjunction with the employment of pizzicato at several junctures, which elicited a similar paradoxical impact, the adornments of the principal melody appeared to augment the atmosphere within the space.")
					wait(2.5)
					Chat("The concluding sections of both episodes feature a dominant preparation, provinding ample time to traverse the distance between my location and the table located in the immediate vicinity.")
					wait(2.5)
					Chat("This particular transition commences in the key of F major, and serves as the initial instance of the aforementioned structural element within the overall musical discourse.")
					wait(2.5)
					Chat("It is worth noting that the inclusion of this dominant preparation serves to facilitate the return to the opening material, providing a sense of cohesion within the overarching musical form.")
					end)
			
					Channel:Button("Eat", function()
					Chat("The nocturne then progresses by a series of modulations to the home key of E flat, anchored by a bass line descending largely by step, whilst I amass the Iberian Filet mignon onto the provided fork.")
					wait(2.5)
					Chat("This modulation is supported by a bass line that follows a stepwise descent, a melodic movement characterized by the movement of individual pitches by intervals of a half step.")
					wait(2.5)
					Chat("As this musical transformation occurs, I am engaged in the task of positioning high-quality wagyu filet mignon onto my fork.")
					wait(2.5)
					Chat("This specific type of beef, known for its superior marbling and flavor, has been deemed Grade-A by an established system of classification.")
					wait(2.5)
					Chat("As I meticulously executed the process of transferring the succulent, bluefin tuna from the serving plate to my own, I made sure to utilize the tines of the fork in a downward projecting manner.")
					wait(2.5)
					Chat("The piece was placed back onto the tonic, E flat, yet disguised by a feint to F Major creating an emphatic cadence that served to add panache to the dining experience.")
					wait(2.5)
					Chat("As I gaze upon the culinary masterpiece that has been placed before me, I am struck by the visual and olfactory appeal of the truffle-butter-infused Japanese Wagyu beef.")
					wait(2.5)
					Chat("It has has been topped with a layer of white truffle and adorned with a generous sprinkling of Matsutake mushrooms.")
					wait(2.5)
					Chat("I observe that the surface of the beef is beginning to emit a thin plume of smoke, which rises upwards in a civilized, spiral-like fashion.")
					wait(2.5)
					Chat("This phenomenon is a well-known characteristic of cooking meats at high temperatures, and is often used by chefs to impart a desired level of flavor and tenderness to the finished dish.")
					wait(2.5)
					Chat("I now retract my mask marginally upwards as to enable me to dine on my meal.")
					wait(2.5)
					Chat("I consume the meals piece by piece deftly, moving on to each one as I do so.")
					wait(2.5)
					Chat("Just as I finish, I take a hold of the napkin and swipe it across my wrist.")
					wait(2.5)
					Chat("I proceed to fold the napkin into a geometric shape with four equal sides, flipping it over and repeating the process on the reverse side to ensure that both sides of the napkin are symmetrically folded.")
					wait(2.5)
					Chat("After utilizing a series of precise hand gestures and movements, I carefully apply a controlled amount of physical force to the lateral edges of the previously folded napkin.")
					wait(2.5)
					Chat("This action causes a discernible and visually perceptible depression or concavity to be formed along the peripheral areas of the napkin.")
					wait(2.5)
					Chat("This serves as a means of augmenting and elevating the overall neat and tidy appearance of the folded napkin to an even greater extent.")
					wait(2.5)
					Chat("I hook the underside of the napkin, pulling outwards, then upwards, creating petals. The napkin now represented a lotus. I place it neatly on the table clear of my utensils.")
					end)
			
					local Server = Window:Server("Defense", "http://www.roblox.com/asset/?id=10600613438")
					local Channel = Server:Channel"Self-Defense"
					Channel:Button("Throw Over Shoulder", function()
					Chat("I would firmly grasp your forearm in my hand.")
					wait(2.5)
					Chat("I would position myself in such a way that your torso is on my back and your arm is situated over my shoulder.")
					wait(2.5)
					Chat("Using your arm as a lever and utilizing my back as the center of gravity, I would execute a movement that would result in you being thrown over my shoulder.")
					wait(2.5)
					Chat("As a result of this action, you would collide with the ground and sustain damage to a section of your thoracic vertebrae.")
					end)
			
					Channel:Button("Break Knee", function()
					Chat("I would now initiate movement in a straight line towards you, using my left leg as the primary point of propulsion.")
					wait(2.5)
					Chat("Using my arms to generate momentum, I would execute a motion akin to a snapping motion, with my shoulders colliding with your leg.")
					wait(2.5)
					Chat("As a result of the force applied, you would lose your balance and fall to the ground.")
					wait(2.5)
					Chat("would rise from my previous position, adjusting my balance to an upright posture.")
					wait(2.5)
					Chat("Through the application of force, I would cause your body to rotate laterally by forcefully rotating your left leg.")
					wait(2.5)
					Chat("Using my legs, I would envelop and secure your right leg, placing you in a leg lock.")
					wait(2.5)
					Chat("Placing my hands on your heel, I would extend my joints backwards while simultaneously executing a snapping motion to impart a rotational force, thus snapping your tibiofemoral joint.")
					end)
			
					Channel:Button("Disarm Gun | Twist", function()
					Chat("I would contort the joint in your lower arm, thus hindering your ability to aim your firearm in my direction.")
					wait(2.5)
					Chat("I would strike the joint in your upper arm with my knee, disrupting your grasp on the gun, resulting in you dropping it and rendering it inoperable.")
					end)
			
					Channel:Button("Disarm Weapon | Swivel", function()
					Chat("I would execute a motion involving the rotation of your arm in a direction perpendicular to the plane of your body, causing your tendons to go in shock and you to lose your grip.")
					wait(2.5)
					Chat("I would deliver a swift, powerful blow to the joint located at the juncture of your upper arm and lower arm, applying an upward force to said joint and thereby causing it to be dislocated.")
					wait(2.5)
					Chat("I would strike your sternum with a closed fist, causing a momentary disturbance in the stability and function of your respiratory systems, leading to the involuntary release of your weapon. ")
					end)
			
					Channel:Button("Disarm Weapon | Snap", function()
					Chat("I now utilize my upper limb to grasp your arm, firmly securing it within the confines of my joint's grasp.")
					wait(2.5)
					Chat("I now rotate my body, positioning myself behind you, out of the range from your weapon.")
					wait(2.5)
					Chat("I re-establish my position within the arm lock by rising once again on your rear flank.")
					wait(2.5)
					Chat("I now forcefully drive my elbow downwards, making contact with your shoulder blade in a quick, jabbing motion.")
					wait(2.5)
					Chat("As a result of the shock imparted upon your scapula, your grip loosens and the weapon falls from your hand.")
					wait(2.5)
					Chat("I maintain control over you by dragging you downwards to waist level and keeping you within range.")
					wait(2.5)
					Chat("Utilizing my lower limb, I send my knee upwards into your chin whilst maintaining a firm grip on your arm.")
					wait(2.5)
					Chat("The force of this motion causes your acromioclavicular joint to snap due to the excessive hyperextension placed upon it.")
					end)
			
					Channel:Button("Get Up", function()
					Chat("I would arise from the location at which I had collapsed, reconstituting my position of balance and stability.")
					end)
			
					Channel:Button("Hoist", function()
					Chat("I'd hoist you over my shoulder, efficaciously carrying you")
					end)
			
					Channel:Button("Tackle", function()
					Chat("I'd charge over to you with my arms open, intending to tackle you")
					wait(2.5)
					Chat("Once I was within grappling range, I'd grip your leg, making you tumble over")
					end)
			
					Channel:Button("Pin Down", function()
					Chat("I'd pin you down to the ground, placing my weight over you")
					end)
			
					Channel:Button("Restrain", function()
					Chat("I'd restrain you, as to hinder you from getting up")
					wait(2.5)
					Chat("I'd place my knee over your legs, pushing down firmly")
					wait(2.5)
					Chat("I'd grip your wrists with my hand rigidly, pushing it down across your waist")
					end)
			
					local Channel = Server:Channel"Retaliate"
					Channel:Button("Break Helmet", function()
					Chat("I'd slam your face into the ground repeatedly, shattering your protective headgear with each impact.")
					end)
			
					Channel:Button("Break Mask", function()
					Chat("I would violently force your face into the ground over and over again, causing your mask to shatter into pieces.")
					end)
			
					Channel:Button("Break Visor", function()
					Chat("I'd slam your face into the ground repeatedly, shattering your eyepiece with each strike.")
					end)
			
					Channel:Button("Break Face", function()
					Chat("I'd violently yank the back of your head, gripping your hair.")
					wait(2.5)
					Chat("I'd relentlessly bash your face into the ground, repeatedly smashing your nose and leaving your face battered and bruised beyond recognition.")
					wait(2.5)
					Chat("I'd push down on your head in with all my might, fracturing your parietal region into a bloody, mangled mess")
					end)
			
					Channel:Button("Slam Against Wall", function()
					Chat("I'd slam you against the wall, forcing the air out of your lungs, and disorienting you")
					end)
			
					Channel:Button("Slam Against Counter", function()
					Chat("I'd slam you against the counter, leaving a bruise on your torso due to the edge of the counter")
					end)
			
					Channel:Button("Slam Against Pillar", function()
					Chat("I'd slam you against the pillar, forcing air out of your lungs, and dazing you")
					end)
			
					Channel:Button("Smash Face Into Wall", function()
					Chat("I'd grasp your hair, clenching it firmly")
					wait(2.5)
					Chat("I'd smash your face into the wall, bruising your cheek, and fracturing your nasal bone")
					end)
			
					Channel:Button("Dodge", function()
					Chat("I'd step aside as to dodge, rendering your move innefective")
					end)
			
					Channel:Button("Catch and Twist Arm", function()
					Chat("I'd seize your arm, locking it in my grip")
					wait(2.5)
					Chat("I'd jab the nerve cluster in your neck with the bottom of my hand")
					wait(2.5)
					Chat("I'd swivel your arm, resulting in your body slamming into the ground")
					end)
			
					Channel:Button("Catch and Sweep Leg", function()
					Chat("I'd snatch your leg, in which it was latched in between my arm and torso")
					wait(2.5)
					Chat("I'd sweep your other leg, resulting in you falling to the ground")
					end)
			
					local Channel = Server:Channel"Counter"
					Channel:Button("AP Round - Head", function()
					Chat("Upon contact with the advanced composite material comprising Nomex and Kevlar fibers, the AP round experiences a significant reduction in its kinetic energy.")
					wait(2.5)
					Chat("The configuration of carbon nanotube-reinforced Dyneema fibers within the mask effectively dissipates the residual kinetic energy as the projectile becomes ensconced.")
					wait(2.5)
					Chat("The inclusion of laminate sheets in a compressed state and the utilization of artificially-coiled carbon-fiber muscle actuators serves to minimize the kinetic shock to a level approaching zero.")
					end)
			
					Channel:Button("AP Rounds - Head", function()
					Chat("Upon contact with the advanced composite material comprising Nomex and Kevlar fibers, the AP rounds experience a significant reduction in their kinetic energy.")
					wait(2.5)
					Chat("The configuration of carbon nanotube-reinforced Dyneema fibers within the mask effectively dissipates the residual kinetic energy as the projectiles become ensconced.")
					wait(2.5)
					Chat("The inclusion of laminate sheets in a compressed state and the utilization of artificially-coiled carbon-fiber muscle actuators serves to minimize the kinetic shocks to a level approaching zero.")
					end)
			
					Channel:Button("AP Round - Torso", function()
					Chat("The AP round twists through my suit as it perforates through the silicon carbide discs")
					wait(2.5)
					Chat("The ceramic matrices and high-modulus polyethylene effectuates the bullet's loss in velocity")
					wait(2.5)
					Chat("The bullet is now lodged in the carbon nanotube-reinforced Dyneema coated in Carbyne LAC")
					wait(2.5)
					Chat("The microlattice absorbing pads and SHOCKtec padding absorb the majority of the impact shock")
					end)
			
					Channel:Button("AP Rounds - Torso", function()
					Chat("The AP rounds twist through my suit as they perforate through the silicon carbide discs")
					wait(2.5)
					Chat("The ceramic matrices and high-modulus polyethylene effectuates the bullets' loss in velocity")
					wait(2.5)
					Chat("The bullets are now lodged in the carbon nanotube-reinforced Dyneema coated in Carbyne LAC")
					wait(2.5)
					Chat("The microlattice absorbing pads and SHOCKtec padding absorb the majority of the impact shock")
					end)
			
					Channel:Separator()
			
					Channel:Button("N-Round - Head", function()
					Chat("The aluminum alloy matrix reinforced by nickel-coated, multi-walled carbon nanotubes in my mask immobilizes the bullet completely")
					wait(2.5)
					Chat("The polyethylene-wrapped silicon-carbide layer under the titanium alloy frame of my mask absorbs the kinetic shock")
					end)
			
					Channel:Button("N-Rounds - Head", function()
					Chat("The aluminum alloy matrix reinforced by nickel-coated, multi-walled carbon nanotubes in my mask immobilizes the bullets completely")
					wait(2.5)
					Chat("The polyethylene-wrapped silicon-carbide layer under the titanium alloy frame of my mask absorbs the kinetic shock")
					end)
			
					Channel:Button("N-Round - Torso", function()
					Chat("The tungsten carbide ceramic plating causes the bullet to lodge itself into the plating causing a dent")
					wait(2.5)
					Chat("The silver-cellulose aerogel along with optical fiber networks keep the structural integrity of the plating intact")
					wait(2.5)
					Chat("The blend of Nomex and Kevlar aramids, with polyethylene sheets sandwiching the plate padding reduces the impact shock")
					end)
			
					Channel:Button("N-Rounds - Torso", function()
					Chat("The tungsten carbide ceramic plating causes the bullets to lodge themselves into the plating causing a dent")
					wait(2.5)
					Chat("The silver-cellulose aerogel along with optical fiber networks keep the structural integrity of the plating intact")
					wait(2.5)
					Chat("The blend of Nomex and Kevlar aramids, with polyethylene sheets sandwiching the plate padding reduces the impact shock")
					end)
			
					Channel:Separator()
			
					Channel:Button("Blade - Head", function()
					Chat("The blade now encounters the Nomex-Kevlar polymer, and as it nudges its way through, its velocity is diminished considerably")
					wait(2.5)
					Chat("The carbon-nanotube reinforced Dyneema fiber network in my mask absorbs the remaining kineticism, as the blade lodged itself there")
					wait(2.5)
					Chat("The accompanying compressed laminate sheets and artificially-coiled carbon-fiber muscle actuators reduce the kinetic shock to near zero")
					end)
			
					Channel:Button("Blade - Torso", function()
					Chat("The tungsten carbide ceramic plating causes the blade to lodge itself into the plating causing a dent")
					wait(2.5)
					Chat("The silver-cellulose aerogel along with optical fiber networks keep the structural integrity of the plating intact")
					wait(2.5)
					Chat("The blend of Nomex and Kevlar aramids, with polyethylene sheets sandwiching the plate padding reduces the impact shock")
					end)
			
					Channel:Separator()
			
					Channel:Button("Blunt Force - Head", function()
					Chat("The aluminum alloy matrix reinforced by nickel-coated, multi-walled carbon nanotubes in my frame immobilizes the momentum completely")
					wait(2.5)
					Chat("The polyethylene-wrapped silicon-carbide layer under the titanium alloy frame of my actuators absorbs the kinetic shock")
					end)
			
					Channel:Button("Blunt Force - Torso", function()
					Chat("The exterior of your weapon twists through my suit as it perforates through the silicon carbide discs")
					wait(2.5)
					Chat("The ceramic matrices and high-modulus polyethylene effectuates the loss in velocity")
					wait(2.5)
					Chat("It is now recoiled back from the carbon nanotube-reinforced Dyneema coated in Carbyne LAC")
					wait(2.5)
					Chat("The microlattice absorbing pads and SHOCKtec padding absorb the majority of the impact shock")
					end)
			
					Channel:Separator()
			
					Channel:Button("Strike - Head", function()
					Chat("The aluminum alloy matrix reinforced by nickel-coated, multi-walled carbon nanotubes in my frame immobilizes the momentum of your strike completely")
					wait(2.5)
					Chat("The polyethylene-wrapped silicon-carbide layer under the titanium alloy frame of my actuators absorbs the kinetic shock")
					wait(2.5)
					Chat("Your limb is recoiled back towards you, with a sharp pain higlighted on it as a result of clashing with the plating")
					end)
			
					Channel:Button("Strike - Torso", function()
					Chat("The exterior of your limb slams against my suit as it collides with the silicon carbide discs")
					wait(2.5)
					Chat("The ceramic matrices and high-modulus polyethylene effectuates the loss in velocity")
					wait(2.5)
					Chat("It is now jerked back from the carbon nanotube-reinforced Dyneema coated in Carbyne LAC")
					wait(2.5)
					Chat("The microlattice absorbing pads and SHOCKtec padding absorb the majority of the impact shock")
					end)
			
					Channel:Separator()
			
					Channel:Button("EMP - Counter", function()
					Chat("The composite of wood cellulose nanofibers and silver nanowires along with the porous structure intercepts the electromagentic blast.")
					wait(2.5)
					Chat("It is now recoiled back from the threaded ports within the expanded polystyrene foam, the blast being dispersed back into the air")
					wait(2.5)
					Chat("The vinyl nitrile foam rigidifies to nullify the rebounding backfire from the dispersion of the blast")
					end)
			
					local Server = Window:Server("Offense", "http://www.roblox.com/asset/?id=10727931672")
					local Channel = Server:Channel"Hand-Hand"
					Channel:Button("Discombobulate", function()
					Chat("I would execute a simultaneous blade-hand attack upon both sides of your cervical region, targeting the neural aggregates, with the intention of disrupting your equilibrium.")
					end)
			
					Channel:Button("Elbow Jaw", function()
					Chat("I'd elbow the right side of your mandible, causing a break in the continuity of the bone structure.")
					end)
			
					Channel:Button("Hammer Fist", function()
					Chat("I would execute an upwards hammer fist strike to your mandible, thereby exposing your laryngeal area.")
					end)
			
					Channel:Button("Damage Windpipe", function()
					Chat("I would implement a kinetic impact upon your larynx, resulting in the occlusion of your trachea.")
					end)
			
					Channel:Button("Traumatize Solar Plexus", function()
					Chat("I would reform my fist in a manner such that it twists upside down, thereby causing my pneumonatic actuators to prompt contraction in a rearward direction.")
					wait(2.5)
					Chat("I would enact a rotational motion with my fist, targeting the superior region of your abdominal cavity, resulting in the activation of the rotary module.")
					wait(2.5)
					Chat("The rotary module exhibits the production of tangential speed through the utilization of the actuators, which are extended in a forward direction at their maximum velocity.")
					wait(2.5)
					Chat("The impact of the blow would make physical contact with the upper region of your abdominal region, traumatizing your solar plexus.")
					end)
			
					Channel:Button("Double-Fist Strike", function()
					Chat("I would execute a double-fist impact maneuver upon your thoracic region, making you tumble rearwards")
					end)
			
					Channel:Button("Spinning Back-Fist", function()
					Chat("I would execute a rotational back fist strike to your facial region, resulting in the rupture of the cheek tissue.")
					end)
			
					Channel:Button("Fracture Ribs", function()
					Chat("I'd knee the side of your abdomen, targeting the lateral region of your abdominal wall, resulting in a fracture within your ribcage.")
					end)
			
					Channel:Button("Shatter Ribs", function()
					Chat("I would execute a back-fist technique to the lateral aspect of your abdominal cavity, resulting in the fragmentation of your pre-existing rib fractures.")
					end)
			
					Channel:Button("Paralyze Arms", function()
					Chat("I would execute a back-fist maneuver, targeting the collarbone region of your body, resulting in temporary paralysis of both upper limbs.")
					end)
			
					Channel:Button("Bash Face Into Knee", function()
					Chat("I would securely grasp the posterior portion of your cranial structure, applying a firm hold on it.")
					wait(2.5)
					Chat("I forcibly moved it downward toward my patella with great force, causing it to follow a straight path towards said joint.")
					wait(2.5)
					Chat("I send my knee upwards towards your nasal cavity, letting it collide, hence bashing in your nose")
					end)
			
					Channel:Button("Clap Ears", function()
					Chat("I'd strike your external auditory canals, thus causing temporary loss of function and tinnitus, due to the transmission of shock waves through the ear drum.")
					end)
			
					Channel:Button("Strike Temple", function()
					Chat("I would deliver a blow to your temporal region with my clenched hand, causing a brief loss of conciousness as your eyes roll over and back to its' intial spot.")
					end)
			
					Channel:Button("Chokehold", function()
					Chat("I'd lunge around you, in a forward thrust of the body, propelling myself toward your posterior region and clenching on your cervical region.")
					wait(2.5)
					Chat("I would encircle my upper extremity around your cervical region, securing it firmly with a vice-like grip.")
					wait(2.5)
					Chat("I would impact the ligamentous tissue surrounding the femur bone, causing you to adopt a position of genuflection.")
					wait(2.5)
					Chat("Utilization of my lower extremities, specifically my quadriceps and tibialis muscles, would enable me to maintain my superior position.")
					wait(2.5)
					Chat("Your blood flow would cut off, causing you to suffer cerebral ischemia, ineluctably making you black out")
					end)
			
					Channel:Button("Open Palm Into Nose", function()
					Chat("I would utilize the dexterous muscles of my hand to propel it towards the anterior region of your face, specifically targeting the nasal bone located within the nasal cavity.")
					wait(2.5)
					Chat("This forceful impact would result in the fracture of said nasal bone and lead to the transfixation of your cerebral cortex, causing damage to your cognitive functions.")
					end)
			
					Channel:Button("Brachial Plexus", function()
					Chat("I would forcibly strike your brachial plexus, a network of nerves located in the upper arm, with my open hand, inducing sensory overload and subsequently render you unconscious.")
					end)
			
					local Channel = Server:Channel"Kicks"
					Channel:Button("Roundhouse Kick", function()
					Chat("I would execute a circumductory strike, targeting your facial region and resulting in a temporary state of unconsciousness due to the kinetic energy transfer upon collision.")
					end)
			
					Channel:Button("Horse Kick", function()
					Chat("I would execute a caprine-inspired rotational movement of the lower extremity, targeting the abdominal region, resulting in significant somatic discomfort in the gastric region.")
					end)
			
					Channel:Button("Axe Kick", function()
					Chat("I would execute an ax kick, a high-velocity with the intention of inhibiting the mobility of your shoulder joint and the musculoskeletal structure of your upper limb.")
					end)
			
					Channel:Button("Crescent Kick", function()
					Chat("I would execute a circumferential kick, utilizing a semi-circular trajectory to impact the auricular limb and facial region.")
					end)
			
					Channel:Button("Front Hook Kick", function()
					Chat("I would execute a front hook kick to deliver a concussive force to the mandibular and zygomatic regions of your craniofacial anatomy, resulting in a posterior momentum-induced loss of balance.")
					end)
			
					Channel:Button("Double Dropkick", function()
					Chat("Utilizing an intentional forward lean, I engage the pneumatic actuators within my lower extremities to produce a burst of force, propelling me in a rapid dash towards you.")
					wait(2.5)
					Chat("As I approach, I elevate the heel of my foot, executing a leap towards your nasal region.")
					wait(2.5)
					Chat("The impact of the kick causes you to lose your balance and fall to the ground due to the overwhelming force exerted on your anterior region.")
					wait(2.5)
					Chat("The recoil from the collision propels me into the air, allowing me to land back on my feet with proper alignment and stability.")
					end)
			
					local Channel = Server:Channel"Gore Combat"
					Channel:Button("Crush Thyroid Gland", function()
					Chat("I would exert a firm grip on your neck, utilizing my fingers to entwine and tighten around the area.")
					wait(2.5)
					Chat("Placing my fingers onto your thyroid gland, I would apply a vigorous amount of pressure, crushing the gland and obstructing your airflow.")
					end)
			
					Channel:Button("Sever Carotid Artery", function()
					Chat("Utilizing an intentional finger extension, I activate a titanium-alloy claw protrusion, effectively creating a blade-like implement.")
					wait(2.5)
					Chat("I angle my wrist towards your sternohyoid muscle, preparing to execute a precise strike.")
					wait(2.5)
					Chat("With a rapid extension of my arm, I successfully penetrate your throat, causing intense bleeding due to the severing of your external carotid artery.")
					end)
			
					Channel:Button("Gauge Eyes Out", function()
					Chat("Utilizing a swift and calculated motion, I would insert my digits into the orbital cavities of your eyes, penetrating the occipital cavity and causing significant damage.")
					wait(2.5)
					Chat("I would then forcefully extract your eyes from their respective sockets, causing irreparable harm to your visual system.")
					end)
			
					Channel:Button("Face Stomp", function()
					Chat("Utilizing a sidekick technique, I target your knee joint, resulting in a tear of the anterior cruciate ligament, causing you to fall to the ground.")
					wait(2.5)
					Chat("I then proceed to stomp on your facial region, utilizing the principle of inertia to cause the bones to cave in.")
					wait(2.5)
					Chat("I execute a kick to your mandibular joint, causing maximal head movement and resulting in the forward displacement of your C2 vertebra, severing your cervical vertebral column.")
					end)
			
					Channel:Button("Crush Head", function()
					Chat("I utilize a firm grasp on both sides of your temporal region, applying a pressure akin to that of a hydraulic press.")
					wait(2.5)
					Chat("The Carbyne LAC within my palms absorbs and distributes the pressure evenly, causing your eyeballs to protrude as your head is compressed.")
					wait(2.5)
					Chat("The Carbyne LAC ingests the majority of the pressure and disperses the energy evenly across the surface of my palm")
					wait(2.5)
					Chat("The structural integrity of your skull is compromised, leading to its crushing under the immense force being applied.")
					end)
			
					Channel:Button("Rip Jaw", function()
					Chat("I would now employ a specific hand placement on your upper and lower jaw, utilizing a simultaneous pulling and pushing motion on the corresponding portions of your jaw.")
					wait(2.5)
					Chat("This action would result in a tearing of your temporal mandibular joint due to the excessive force applied to your mandible.")
					wait(2.5)
					Chat("The resilience of your jaw would be surpassed, resulting in a tearing of the skin, tissue, and muscles, leaving the lower portion of your jaw dangling.")
					end)
			
					Channel:Button("Sever Tongue", function()
					Chat("I extend my hand towards your jaw, utilizing physical force to open the mandible and create an opening.")
					wait(2.5)
					Chat("I insert my hand further into the cavity, navigating through the esophageal passage until I reach the distal end of your lingual organ.")
					wait(2.5)
					Chat("I exert a strong and sustained pull, forcibly removing the tongue from its' cavity.")
					end)
			
					local Channel = Server:Channel"Robot Combat"
					Channel:Button("Unholster LI Baron", function()
					Chat("I'd now slip my hand into the top portion of my suit, just towards my collar.")
					wait(2.5)
					Chat("I'd clutch on the contoured grip of my ZR Baron, as my fingers wrap around it in an arc.")
					wait(2.5)
					Chat("I'd push my finger onto the safety lever, flicking the safety off, and thus permitting the discharge mechanism.")
					wait(2.5)
					Chat("I'd now pull on the handle, taking the firearm out of my suit, and exposing it.")
					end)
			
					Channel:Button("Holster LI Baron", function()
					Chat("I'd now switch the safety of the ZR Baron on once more")
					wait(2.5)
					Chat("I'd now lodge it once more into the concordant place on my suit")
					end)
			
					Channel:Button("Load AP LI Baron", function()
					Chat("I'd push on the ZR Baron's ammunition latch, flicking it open")
					wait(2.5)
					Chat("I'd press down on the ejection pin, making the rounds loose")
					wait(2.5)
					Chat("I'd tap on the cylinder conscientiously, letting the rounds fall")
					wait(2.5)
					Chat("I'd now reach over into my suit, taking out AP cartridges")
					wait(2.5)
					Chat("I'd now load them into the cylinder indvidually at a fast rate")
					wait(2.5)
					Chat("I'd push on the latch again, flicking it close")
					end)
			
					Channel:Button("AP Left Arm", function()
					Chat("I'd now aim at the mechanical joints on your left arm")
					wait(2.5)
					Chat("I'd pull on the trigger, sending the bullet soaring through the air")
					wait(2.5)
					Chat("The bullet would collide with the joint, completely severing your left arm")
					end)
			
					Channel:Button("AP Right Arm", function()
					Chat("I'd now aim at the mechanical joints on your right arm")
					wait(2.5)
					Chat("I'd tug on the trigger, sending the bullet hurtling towards them")
					wait(2.5)
					Chat("The bullet would ram into the joint's hinge, leaving the right arm dangling")
					end)
			
					Channel:Button("EMP", function()
					Chat("I'd now reach into my suit, gripping something")
					wait(2.5)
					Chat("I'd take out a magnetic interlocking EMP")
					wait(2.5)
					Chat("I'd charge up to them without hesitation")
					wait(2.5)
					Chat("I'd strap the EMP on them, which was ready to be triggered")
					wait(2.5)
					Chat("I'd trigger the EMP, shutting them down")
					end)
			
					Channel:Button("Flash", function()
					Chat("I'd now reach into my pocket, pincing on something metallic")
					wait(2.5)
					Chat("I'd activate the device in my pocket")
					wait(2.5)
					Chat("I'd take out a laser pointer, which was activated")
					wait(2.5)
					Chat("I'd flash it at your optics, blinding you temporarily")
					end)
			
					local Channel = Server:Channel"Melee Combat"
					Channel:Button("Unsheathe Sleeve", function()
					Chat("I'd trigger the mechanical sheathe in my hand, ejecting the blade")
					wait(2.5)
					Chat("I'd now grip the blade, inclined to strike")
					end)
			
					Channel:Button("Sever Artery", function()
					Chat("I'd now swing my knife, which was angled towards your neck, lacerating your cartilage")
					wait(2.5)
					Chat("I'd now yank the blade back, retracting it out of your neck")
					wait(2.5)
					Chat("I'd now jab my knife, whereas its edge was angled towards your larynx")
					wait(2.5)
					Chat("The stab would pierce far enough to sever your carotid artery and jugular vein")
					wait(2.5)
					Chat("The lack of blood supply towards your brain, due to your carotid artery being severed, would kill you")
					wait(2.5)
					Chat("I'd yank my blade back, placing it in my grip again")
					end)
			
					Channel:Button("Stab Nerve Cluster", function()
					Chat("I'd now jab my blade into your scalene muscles, just above the clavicle")
					wait(2.5)
					Chat("The blade would thrust into a nerve cluster, severing multiple nerves")
					wait(2.5)
					Chat("I'd yank my blade back, placing it in my grip again")
					end)
			
					Channel:Button("Stab Armpit", function()
					Chat("I'd now grip my blade upright again, angling the tip towards your armpit")
					wait(2.5)
					Chat("I'd broaden my arm in a snapping motion, jabbing the knife's end at your armpit")
					wait(2.5)
					Chat("The axillary artery would be severed, crippling both your arms and fingers due to the lack of blood")
					wait(2.5)
					Chat("I'd yank my blade back, placing it in my grip again")
					end)
			
					Channel:Button("Sheathe Sleeve", function()
					Chat("I'd now relinquish the blade from my grip, letting it dangle on its string")
					wait(2.5)
					Chat("I'd now trigger the mechanical sheathe once again, whereas the blade would retract back into my sleeve")
					end)
			
					Channel:Button("Unsheathe Cloak", function()
					Chat("I'd now place my hand underneath my suit, gripping the handle of two blades")
					wait(2.5)
					Chat("I'd pull on the handles, unraveling the blades out of my suit")
					end)
			
					Channel:Button("Throw Blades", function()
					Chat("I'd now swivel the blades into the gap between middle and ring fingers, in both hands")
					wait(2.5)
					Chat("Aiming towards you, I'd retract my arm")
					end)
			
					Channel:Button("Head", function()
					Chat("The blades would pierce through the craniocerebral region")
					wait(2.5)
					Chat("Due to the nerve damage, your air circulation would cut off, concluding in you dying from hypoxia")
					end)
			
					Channel:Button("Lungs", function()
					Chat("The blades would pierce through your lungs, passing right through the ribcage")
					wait(2.5)
					Chat("Due to the pulmonary hemorrhage, they would be unable to speak nor move, as they drowned in your blood")
					end)
			
					Channel:Button("Femur", function()
					Chat("The blades would pierce through your rectus femoris muscle")
					wait(2.5)
					Chat("The femoral artery would be severed, resulting in massive blood loss, and paralysis of the lower body")
					end)
					local Server = Window:Server("Fiearms", "http://www.roblox.com/asset/?id=10600612613")
					local Channel = Server:Channel"Firearms"
					Channel:Button("Unholster Px4-SC", function()
					Chat("I'd now slide my hand inside the top portion of my suit, towards my collar.")
					wait(2.5)
					Chat("I'd arc my fingers, wrapping them around and clutching on the contoured grip of my Px4 Storm Compact.")
					wait(2.5)
					Chat("I'd push my finger onto the safety lever, flicking the safety off, and thus permitting the discharge mechanism.")
					wait(2.5)
					Chat("I'd now pull on the handle, taking the firearm out of my suit, and exposing it.")
					end)
			
					Channel:Button("Fire | Rupture Spine", function()
					Chat("I'd now drive its muzzle against your solar plexus, creating a semicircular laceration")
					wait(2.5)
					Chat("I'd now fire rapidly, blasting the full clip into your torso")
					wait(2.5)
					Chat("The ported barrel minimizes the muzzle flip and perceived recoil")
					wait(2.5)
					Chat("The Gemtech Lunar-45 suppresses the muzzle blast and noise emanating from the firearm")
					wait(2.5)
					Chat("Your mesenteric artery gets struck by one of the shots, subsequently severing it")
					wait(2.5)
					Chat("Your spinal column is ruptured by numerous of the rounds")
					wait(2.5)
					Chat("Your abdominal cavity is in full disorder, as overwhelming pain surges through your body")
					end)
			
					Channel:Button("Holster Px4-SC", function()
					Chat("I'd now place my thumb onto the safety lever, switching the safety of the Px4 SC on once more.")
					wait(2.5)
					Chat("I'd now lodge it once more into the concordant place on my suit")
					end)
			
					Channel:Separator()
			
					Channel:Button("Unholster LI Breaker", function()
					Chat("I'd now insert my hand inside the rear of my suit, slightly above my belt.")
					wait(2.5)
					Chat("I'd clutch on the textured grip of my ZR Breaker, as my fingers wrap around it in an arc.")
					wait(2.5)
					Chat("I'd push my finger onto the safety lever, flicking the safety off, and thus permitting the discharge mechanism.")
					wait(2.5)
					Chat("I'd now pry on the grip, taking the firearm out of my suit, and exposing it")
					end)
			
					Channel:Button("Fire | Myocardial Ischemia", function()
					Chat("I'd now aim at your center mass")
					wait(2.5)
					Chat("I'd pull on the trigger, firing off 4 times, and sending 2 rounds into your infraclavicular region")
					wait(2.5)
					Chat("The other 2 is sent into your pericardial cavity")
					wait(2.5)
					Chat("Your coronary artery, brachial artery, and axillary artery is severed")
					wait(2.5)
					Chat("You fall onto the ground as liquids develop in your pericardium")
					wait(2.5)
					Chat("Due to the absence of blood supply towards your heart, you fail to circulate blood")
					wait(2.5)
					Chat("You eventually die due to myocardial ischemia")
					end)
			
					Channel:Button("Holster LI Breaker", function()
					Chat("I'd flick the safety, disabling the discharge mechanism.")
					wait(2.5)
					Chat("I'd slide the ZR Breaker into the corresponding area on my suit.")
					end)
			
					Channel:Separator()
					Channel:Button("Unholster LI Baroness", function()
					Chat("I'd now reach inside the top portion of my suit, towards my collar.")
					wait(2.5)
					Chat("I'd clutch on the contoured grip of my ZR Baroness, as my fingers wrap around it in an arc.")
					wait(2.5)
					Chat("I'd push my finger onto the safety lever, flicking the safety off, and thus permitting the discharge mechanism.")
					wait(2.5)
					Chat("I'd now pull on the handle, taking the firearm out of my suit, and exposing it.")
					end)
			
					Channel:Button("Fire | Sever Brain Stem", function()
					Chat("I'd now wrap my right arm around your neck")
					wait(2.5)
					Chat("I'd now ram the muzzle of the ZR Baroness into your neck")
					wait(2.5)
					Chat("I angle the muzzle towards the brain stem")
					wait(2.5)
					Chat("I fire off, sending 3 rounds into the foundation of your skull")
					wait(2.5)
					Chat("Your entire body is nulled as your brain stem is severed")
					wait(2.5)
					Chat("The hydrostatic pressure of the round hitting the spinal fluid kills the brain")
					end)
			
					Channel:Button("Holster LI Baroness", function()
					Chat("I'd now switch the safety of the ZR Baroness on once more")
					wait(2.5)
					Chat("I'd now lodge it once more into the concordant place on my suit")
					end)
			
					Channel:Separator()
					Channel:Button("Unholster LI Baron", function()
					Chat("I'd now slip my hand into the top portion of my suit, just towards my collar.")
					wait(2.5)
					Chat("I'd clutch on the contoured grip of my ZR Baron, as my fingers wrap around it in an arc.")
					wait(2.5)
					Chat("I'd push my finger onto the safety lever, flicking the safety off, and thus permitting the discharge mechanism.")
					wait(2.5)
					Chat("I'd now pull on the handle, taking the firearm out of my suit, and exposing it.")
					end)
			
					Channel:Button("Fire | Headshot", function()
					Chat("I'd now angle the barrel directly to your temporal region")
					wait(2.5)
					Chat("I'd now fire off, the pneumatic drive sending a pyroelectric current across the barrel, thus hurling the duplex cartridge against the carrier rail and into your skull")
					wait(2.5)
					Chat("The bullet shoves its way through your prefrontal cortex, the main cartridge breaking apart upon making contact with the frontal layer of your skull")
					wait(2.5)
					Chat("Your tissues snap back toward the initial opening and overshoot their original position due to the inertial pressure embedded into the entry point")
					wait(2.5)
					Chat("The flow velocity accompanied by the constructive interference causes your tissue cavity to transition outwards into an impact fan then implode")
					wait(2.5)
					Chat("The kinetic force propagated from the duplex cartridge along with the entropic disturbance within your skull kills you instantly")
					end)
			
					Channel:Button("Holster LI Baron", function()
					Chat("I'd now switch the safety of the ZR Baron on once more")
					wait(2.5)
					Chat("I'd now lodge it once more into the concordant place on my suit")
					end)
			
					local Server = Window:Server("Wisdom", "http://www.roblox.com/asset/?id=10600615928")
					local Channel = Server:Channel"Thoughts"
					Channel:Button("Analyst", function()
					Chat("I began to ponder over why mental features discoursed of as the analytical, are, in themselves, but little susceptible to analysis.")
					wait(2.5)
					Chat("As the strong man exults in their physical ability, delighting in such exercises as calling their muscles into action, so glories the analyst in that moral activity which disentangles.")
					wait(2.5)
					Chat("I reached into the inner workings of my vest, clenching a notepad and flipping it out. A myriad of enigmas, conundrums, and hieroglyphics were exhibited.")
					wait(2.5)
					Chat("Along the writings were an individual degree of acumen per solution, which, to the ordinary apprehension, seemed preternatural.")
					wait(2.5)
					Chat("The faculty of re-solution is possibly much invigorated by mathematical study, and especially by that highest branch of it which, unjustly, and merely on account of its retrograde operations.")
					wait(2.5)
					Chat("Yet to calculate is not in itself to analyze. It presents a somewhat peculiar narrative by observations very much at random.")
					wait(2.5)
					Chat("Therefore, I wish to assert that the higher powers of the reflective intellect are more decidedly and more usefully tasked by individual incentives rather than collective interests.")
					wait(2.5)
					Chat("The attention is here called powerfully into play. If it lags for an instant, an oversight is committed, resulting in injury or, worse, defeat.")
					wait(2.5)
					Chat("The possible moves being not only manifold but involute, the chances of such oversights are multiplied; and in nine cases out of ten, it is the more concentrative rather than the more acute fighter who conquers.")
					wait(2.5)
					Chat("On the contrary, where the moves are unique and have but little variation, the probabilities of inadvertence are diminished. ")
					wait(2.5)
					Chat("The mere attention being left comparatively what advantages are obtained by either party are obtained by superior precision.")
					wait(2.5)
					Chat("It has long been noted for its influence upon what is termed the calculating power, and men of the highest order of intellect have been known to take an unaccountable delight in it.")
					wait(2.5)
					Chat("To play illegitimately requires a certain broadness of knowledge, which includes a comprehension of all the sources whence a loophole or advantage may be derived.")
					wait(2.5)
					Chat("These are not only manifold but multiform, and lie frequently among recesses of thought altogether inaccessible to the ordinary understanding.")
					wait(2.5)
					Chat("Thus to have a retentive memory, and to proceed by “the book,” are points commonly regarded as the sum total of good playing.")
					wait(2.5)
					Chat("But it is in matters beyond the limits of mere rule that the skill of the analyst is evinced.")
					wait(2.5)
					Chat("The analytical power should not be confounded with simple ingenuity; for while the analyst is necessarily ingenious, the ingenious man is often remarkably incapable of analysis.")
					wait(2.5)
					Chat("It will be found, in fact, that the ingenious are always fanciful, and the truly imaginative never otherwise than analytic.")
					wait(2.5)
					Chat("I make, in silence, a host of observations and inferences around the bar. The difference in the extent of the information obtained lies not so much in the validity of the inference as in the quality of the observation.")
					wait(2.5)
					Chat("The necessary knowledge is that of what to observe.") 	
					end)
				else
					-- Create a notification with the given parameters
					CreateNotification("Access denied.", "http://www.roblox.com/asset/?id=11533060886", 5)
			end
		end)
